{% set name = "PyJWT" %}
{% set version = "1.5.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "500be75b17a63f70072416843dc80c8821109030be824f4d14758f114978bae7" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  entry_points:
    - jwt = jwt.__main__:main
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - cryptography >=1.4
    - flake8
    - flake8-import-order
    - pep8-naming

test:
  imports:
    - jwt
    - jwt.contrib
    - jwt.contrib.algorithms

  commands:
    - jwt --help

about:
  home: https://github.com/jpadilla/pyjwt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'JSON Web Token implementation in Python'
  dev_url: https://github.com/jpadilla/pyjwt
  doc_url: https://pyjwt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
