{% set name = "pyjwt" %}
{% set version = "2.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7628a7eb7938959ac1b26e819a1df0fd3259505627b575e4bad6d08f76db695c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
  run_constrained:
    - cryptography >=3.4.0

test:
  requires:
    - pip
  imports:
    - jwt
  commands:
    - pip check

about:
  home: https://github.com/jpadilla/pyjwt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JSON Web Token implementation in Python
  dev_url: https://github.com/jpadilla/pyjwt
  doc_url: https://pyjwt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - xylar
