{% set name = "pyjwt" %}
{% set version = "2.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyJWT-{{ version }}.tar.gz
  sha256: 57e28d156e3d5c10088e0c68abb90bfac3df82b40a71bd0daa20c65ccd5c23de

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
  run_constrained:
    - cryptography >=3.3.1

test:
  requires:
    - pip
  imports:
    - jwt
  commands:
    - pip check

about:
  home: https://github.com/jpadilla/pyjwt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JSON Web Token implementation in Python
  dev_url: https://github.com/jpadilla/pyjwt
  doc_url: https://pyjwt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
