schema_version: 1

context:
  name: pyjwt
  version: "2.11.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 35f95c1f0fbe5d5ba6e43f00271c275f7a1a4db1dab27bf708073b75318ea623

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
  run_constraints:
    - cryptography >=3.4.0

tests:
  - python:
      imports:
        - jwt
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  license: MIT
  license_file: LICENSE
  summary: JSON Web Token implementation in Python
  homepage: https://github.com/jpadilla/pyjwt
  repository: https://github.com/jpadilla/pyjwt
  documentation: https://pyjwt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - xylar
