schema_version: 1

context:
  name: pyjwt
  version: 2.12.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: c74a7a2adf861c04d002db713dd85f84beb242228e671280bf709d765b03672b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=77.0.3
  run:
    - python >=${{ python_min }}
    - typing_extensions >=4.0
  run_constraints:
    - cryptography >=3.4.0

tests:
  - python:
      imports:
        - jwt
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: JSON Web Token implementation in Python
  homepage: https://github.com/jpadilla/pyjwt
  repository: https://github.com/jpadilla/pyjwt
  documentation: https://pyjwt.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - xylar
